# Generated by Django 3.2.10 on 2021-12-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tag_name',
            new_name='tag_title',
        ),
    ]
